server:
  port: 0 # случайный свободный порт

logging:
  level:
    root: DEBUG
#    org.springframework.web: INFO
#    org.springframework.security: INFO
#    org.springframework.security.oauth2: INFO
#    org.springframework.boot.autoconfigure: DEBUG
#    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

spring:
  # Security (jwt) properties
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000

  application:
    name: product-service # имя сервиса для eureka

  # MongoDB properties
  data:
    mongodb:
      database: product
      port: 27117
      host: localhost

# Eureka properties
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka # для регистрации в eureka

# Mongock properties
mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.product.mongock.changelog
